# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Links: /friends
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- Introduction
- categories
- information


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter: vensing
google_plus:
fb_admins:
fb_app_id:

# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config  
## highlight in frontend, the plugin (backend) just do some prepare work. 
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start 
hljs:
  enable: true 
  #true to enable the plugin 
  line_number: frontend 
  # add line_number in frontend or backend 
  trim_indent: backend 
  # trim the indent of code block to prettify output. backend or front-end (recommend) 
  copy_code: true 
  # show copy code in caption. 
  label:
    left: Code
    right: ':'
    copy: Copy Code